-- Initial table
CREATE TABLE IF NOT EXISTS user (
  user_pk INTEGER NOT NULL PRIMARY KEY UNIQUE,
  last_name TEXT NOT NULL,
  first_name TEXT NOT NULL,
  middle_name TEXT,
  extension TEXT,
  designation TEXT
);
CREATE TABLE IF NOT EXISTS log (
  log_pk INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_fk INTEGER NOT NULL,
  date TEXT(10) NOT NULL,
  time TEXT(8) NOT NULL,
  FOREIGN KEY (user_fk) REFERENCES user (user_pk) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS user_pref (
  pref_key TEXT PRIMARY KEY UNIQUE NOT NULL,
  pref_value TEXT
);
CREATE TABLE IF NOT EXISTS leave_application (
  leave_pk INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_fk INTEGER NOT NULL,
  date_file TEXT DEFAULT CURRENT_DATE,
  is_approved INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_fk) REFERENCES user (user_pk) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS leave_date (
  date_record_pk INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  leave_fk INTEGER NOT NULL,
  date_value TEXT NOT NULL,
  FOREIGN KEY (leave_fk) REFERENCES leave_application (leave_pk) ON DELETE CASCADE
);